"""重新修改User

Revision ID: 845389b90ea2
Revises: 5db62846ab0e
Create Date: 2020-05-12 13:38:07.526037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845389b90ea2'
down_revision = '5db62846ab0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token')
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
